version: "3"

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-patients
    ports:
      - ${APP_PORT_EXT}:${APP_PORT}
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
    networks:
      - patients-network
  postgres:
    image: postgres:latest
    container_name: postgres-patients
    ports:
      - 5433:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - patients-network

volumes:
  db-data:

networks:
  patients-network:
    driver: bridge
